sudo: false

language: go

# Thanks to the gist: https://gist.github.com/m3t/df29ec4e0aae167f99c8#file-travis-yml
# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - git submodule update --init --remote --recursive

install: go get -v github.com/gohugoio/hugo

script:
  - hugo

deploy:
  provider: pages
  skip_cleanup: true
  # token is set in travis-ci.org dashboard
  github_token: $GITHUB_API_KEY
  on:
    branch: master
  local_dir: public
  repo: bioinformatist/bioinformatist.github.io
  target_branch: master
  email: deploy@travis-ci.org
  name: deployment-bot